# Generated by Django 2.1.2 on 2018-11-22 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolinfo.TeacherInfo')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('max_number', models.PositiveIntegerField(default=0, verbose_name='最大指导学生人数')),
                ('rest_number', models.PositiveIntegerField(default=0, verbose_name='剩余指导学生人数')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '教师',
                'ordering': ['-rest_number'],
            },
            bases=('schoolinfo.teacherinfo',),
        ),
    ]
