# Generated by Django 2.1.2 on 2018-11-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-rest_number'], 'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
