# Generated by Django 2.1.2 on 2018-11-22 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(choices=[('all', '全体教师和学生'), ('all_student', '全体学生'), ('all_teacher', '全体教师'), ('no_thesis_student', '未选题学生'), ('thesis_student', '已选题学生')], max_length=20)),
                ('text', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '公告栏',
                'ordering': ['-pub_time'],
            },
        ),
    ]
