# Generated by Django 2.1.2 on 2018-11-22 08:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisagreeThesisReson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='理由')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '论文标签',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='论文题目')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='选题内容')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('is_choiced', models.BooleanField(default=False, verbose_name='已有学生选择')),
                ('need_verify', models.BooleanField(default=True, verbose_name='待审核')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('tags', models.ManyToManyField(blank=True, to='thesis.Tag', verbose_name='选题标签')),
            ],
            options={
                'verbose_name_plural': '论文题目',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AddField(
            model_name='disagreethesisreson',
            name='thesis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thesis.Thesis', verbose_name='论文题目'),
        ),
        migrations.AlterUniqueTogether(
            name='thesis',
            unique_together={('title', 'publisher')},
        ),
    ]
