# Generated by Django 2.1.2 on 2018-11-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='need_verify',
            field=models.BooleanField(default=False, verbose_name='待审核'),
        ),
    ]
