# Generated by Django 2.1.2 on 2018-11-22 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('thesis', '0001_initial'),
        ('teacher', '0001_initial'),
        ('schoolinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': '学生收藏选题表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolinfo.StudentInfo')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('is_choiced_thesis', models.BooleanField(default=False, verbose_name='是否选题')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher', verbose_name='指导老师')),
                ('thesis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='thesis.Thesis', verbose_name='论文选题')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name_plural': '学生',
            },
            bases=('schoolinfo.studentinfo',),
        ),
        migrations.AddField(
            model_name='collection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('student', 'object_id', 'content_type')},
        ),
    ]
